---
dnsmasq_dhcp_range: 192.168.56.10,192.168.56.100
dnsmasq_router: 192.168.56.1
pxe_kickstart_host: 192.168.56.2
install_isos:
  -
    name: Ubuntu-Xenial-amd64-netboot
    filename: mini
    url: http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/
    checksum: md5:76d3b37ea78a6848379fbdab9f0f0c55
    kernel: linux
    initrd: initrd.gz
    boot_files: [ linux, initrd.gz ]

pxe_installers:
  -
    name: Arch
    url: https://www.archlinux.org/static/netboot/ipxe.8da38b4a9310.pxe
    sig: https://www.archlinux.org/static/netboot/ipxe.pxe.919b21409aa7.sig

kickstart_host_vars:
  server:
    centos_7_x86_64:
      url:

  default:
    hostname: pxefresh.local
    networks:
      -
        device: enp0s8
        bootproto: dhcp
