---
dnsmasq_dhcp_range: 192.168.42.10,192.168.42.100
dnsmasq_router: 192.168.42.1
pxe_kickstart_host: 192.168.42.2
install_isos:
  -
    name: Ubuntu-Xenial-amd64-netboot
    filename: mini
    url: http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot
    checksum: md5:fe495d34188a9568c8d166efc5898d22
    kernel: linux
    initrd: initrd.gz
    boot_files: [ linux, initrd.gz ]

kickstart_host_vars:
  server:
    centos_7_x86_64:
      url:

  default:
    hostname: pxefresh.local
    networks:
      -
        device: enp0s8
        bootproto: dhcp
